version: '2'
services:
  web:
    image: 'auth_service'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/auth_service
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: 'postgres'
    image: 'postgres:11.2'
    env_file: '.env'
    ports:
      - "5432:5432"
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

volumes:
  pgdata:
